#aliases
alias batcap='upower -i /org/freedesktop/UPower/devices/battery_BAT0'
alias b='brave-browser --incognito'
alias dir='dir --color=auto'
alias egrep='egrep --color=auto'
alias fgrep='fgrep --color=auto'
alias grep='grep --color=auto'
alias intel2amd='xrandr --setprovideroffloadsink 1 0'
alias la='ls -lha'
alias le='less'
alias ll='ls -lh'
alias ls='ls --color=auto'
alias mac='~/sc/mac.sh'
alias oj='docker run --rm -p 3001:3000 bkimminich/juice-shop'
alias py='python3'
alias tmux='tmux -u'
alias tun='ip addr show tun0 | grep brd | awk -F " " '{print$2}' |  cut -d "/" -f1 '
alias umute='~/sc/umute.sh'
alias up='python -m SimpleHTTPServer 8000 '
alias vdir='vdir --color=auto'
alias v='vim'
alias wam='DRI_PRIME=1'
alias wttr='~/sc/wttr.sh'
alias xo='xdg-open'
alias yeet='~/sc/yeet.sh'
alias ympv='mpv --ytdl-format=18 --fs'
alias yolo='cmatrix -C'
